namespace Infogroup.IDMS.BatchQueues
{
    public enum BatchProcessType
    {
        ZipLoad = 1,
        FileSuppression = 2,
        TouchOrderFiles = 3,
        AddLevel2 = 4,
        AddCalculatedField = 5,
        DDRegen = 6,
        LinkExperian = 7,
        LinkMGEN = 8,
        SearchAndDelete = 9,
        AuditReport = 10,
        BuildReport = 11,
        BuildsByList = 12,
        BradUsage = 13,
        HighValue = 14,
        KarlUsage = 15,
        McGraw = 16,
        OPUUsage = 17,
        PentonUsage = 18,
        ShippingReport = 19,
        ZiffDavisUsage = 20,
        FileCleanup = 21,
        ArchiveMaintenance = 22,
        MoveList = 23,
        DDUpdate = 24,
        DataCard = 25,
        ExperianRoyalty = 26,
        MGENRoyalty = 27,
        FileSuppressionBackout = 28,
        LinkTargetReady = 29,
        EmailAuditReport = 30,
        MGENDD = 31,
        LinkEventTable = 32,
        MoveMGENOPU = 33,
        OPUOnFile = 34,
        AddOfflineModel = 35,
        MGENDDHH = 36,
        SpecialQuery = 37,
        SetBitwiseColumn = 38,
        NightlyCleanup = 39,
        AutoLoadDM = 40,
        OpenOrders = 41,
        ShippingOrders = 42,
        ShippingOrders_csv = 43,
        RestoreArchive = 44,
        LinkTargetWise = 45,
        SetValidEmailFlag = 46,
        MatchAppendTask = 47,
        ExportListConversion = 48,
        ApogeeCustomTask = 49,
        ApogeeExportPointInTimeData = 50,
        SearchOrderHistorybyKey = 51,
        CopyBuildTask = 52,
        OptOutAndHardBounceFile = 53,
        ExportEmailHygiene = 54,
        ImportEmailHygiene = 55,
        ActivateLinkTable = 56,
        CloseNotificationJob = 57,
        DeleteBuild = 58,
        PenetrationReportOne = 59,
        BulkUploadListAction = 60,
        ModelCrossTabReport = 61
    }

    public enum BatchQueueStatus
    {
        Failed = -1,
        Waiting = 0,
        Running = 1,
        Stopped = 88,
        Completed = 99
    }
}