//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDMSCommonService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IDMSCommonService.IIDMSIQService")]
    public interface IIDMSIQService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/GetRandomSampleForSegment", ReplyAction="http://tempuri.org/IIDMSIQService/GetRandomSampleForSegmentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.GetRandomSampleForSegmentResponse> GetRandomSampleForSegmentAsync(IDMSCommonService.GetRandomSampleForSegmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/GetQuickCount", ReplyAction="http://tempuri.org/IIDMSIQService/GetQuickCountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.GetQuickCountResponse> GetQuickCountAsync(IDMSCommonService.GetQuickCountRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IIDMSIQService/GetReport", ReplyAction = "http://tempuri.org/IIDMSIQService/GetReportResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.GetReportResponse> GetReport(IDMSCommonService.GetReportRequest request);

        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/GetDWRecords", ReplyAction="http://tempuri.org/IIDMSIQService/GetDWRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.GetDWRecordsResponse> GetDWRecordsAsync(IDMSCommonService.GetDWRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/DeleteDWRecords", ReplyAction="http://tempuri.org/IIDMSIQService/DeleteDWRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.DeleteDWRecordsResponse> DeleteDWRecordsAsync(IDMSCommonService.DeleteDWRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/GetBuildDataFromSybaseIQ", ReplyAction="http://tempuri.org/IIDMSIQService/GetBuildDataFromSybaseIQResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.GetBuildDataFromSybaseIQResponse> GetBuildDataFromSybaseIQAsync(IDMSCommonService.GetBuildDataFromSybaseIQRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/TestCalculatedField", ReplyAction="http://tempuri.org/IIDMSIQService/TestCalculatedFieldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.TestCalculatedFieldResponse> TestCalculatedFieldAsync(IDMSCommonService.TestCalculatedFieldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/DoIQOperation", ReplyAction="http://tempuri.org/IIDMSIQService/DoIQOperationResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.DoIQOperationResponse> DoIQOperationAsync(IDMSCommonService.DoIQOperationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/SuspendCountSQL", ReplyAction="http://tempuri.org/IIDMSIQService/SuspendCountSQLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.SuspendCountSQLResponse> SuspendCountSQLAsync(IDMSCommonService.SuspendCountSQLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/ValidateOutputFields", ReplyAction="http://tempuri.org/IIDMSIQService/ValidateOutputFieldsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.ValidateOutputFieldsResponse> ValidateOutputFieldsAsync(IDMSCommonService.ValidateOutputFieldsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/VerifyCountInputs", ReplyAction="http://tempuri.org/IIDMSIQService/VerifyCountInputsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.VerifyCountInputsResponse> VerifyCountInputsAsync(IDMSCommonService.VerifyCountInputsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/ImportGUIOrder", ReplyAction="http://tempuri.org/IIDMSIQService/ImportGUIOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.ImportGUIOrderResponse> ImportGUIOrderAsync(IDMSCommonService.ImportGUIOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/VerifyFilterValidations", ReplyAction="http://tempuri.org/IIDMSIQService/VerifyFilterValidationsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.VerifyFilterValidationsResponse> VerifyFilterValidationsAsync(IDMSCommonService.VerifyFilterValidationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/VerifyGeoRadius", ReplyAction="http://tempuri.org/IIDMSIQService/VerifyGeoRadiusResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.VerifyGeoRadiusResponse> VerifyGeoRadiusAsync(IDMSCommonService.VerifyGeoRadiusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/OnBillingStatusChange", ReplyAction="http://tempuri.org/IIDMSIQService/OnBillingStatusChangeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.OnBillingStatusChangeResponse> OnBillingStatusChangeAsync(IDMSCommonService.OnBillingStatusChangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/SaveSummaryReport", ReplyAction="http://tempuri.org/IIDMSIQService/SaveSummaryReportResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.SaveSummaryReportResponse> SaveSummaryReportAsync(IDMSCommonService.SaveSummaryReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIDMSIQService/ListOfSegmentDump", ReplyAction="http://tempuri.org/IIDMSIQService/ListOfSegmentDumpResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IDMSServiceResponse))]
        System.Threading.Tasks.Task<IDMSCommonService.ListOfSegmentDumpResponse> ListOfSegmentDumpAsync(IDMSCommonService.ListOfSegmentDumpRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class DumpResponse : IDMSServiceResponse
    {
        
        private IDMSCommonService.ArrayOfXElement dumpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public IDMSCommonService.ArrayOfXElement Dump
        {
            get
            {
                return this.dumpField;
            }
            set
            {
                this.dumpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/DW.Bizness.Common.Services.Modal")]
    public partial class DWModal
    {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string cityField;
        
        private string firstNameField;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string keyFieldField;
        
        private string lastNameField;
        
        private string stateField;
        
        private string zipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string KeyField
        {
            get
            {
                return this.keyFieldField;
            }
            set
            {
                this.keyFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class ErrorEnvelop
    {
        
        private string detailsField;
        
        private string internalExceptionField;
        
        private string messageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string InternalException
        {
            get
            {
                return this.internalExceptionField;
            }
            set
            {
                this.internalExceptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string StackTrace
        {
            get
            {
                return this.stackTraceField;
            }
            set
            {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VerifyCountInputs))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DumpDataTableResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeleteRecordResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListRecordResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetReportResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(QuickCountResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DumpResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class IDMSServiceResponse
    {
        
        private ErrorEnvelop errorField;
        
        private bool isSuccessField;
        
        private bool isSuccessFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public ErrorEnvelop Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsSuccess
        {
            get
            {
                return this.isSuccessField;
            }
            set
            {
                this.isSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSuccessSpecified
        {
            get
            {
                return this.isSuccessFieldSpecified;
            }
            set
            {
                this.isSuccessFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class VerifyCountInputs : IDMSServiceResponse
    {
        
        private bool isVerifyCountInputsField;
        
        private bool isVerifyCountInputsFieldSpecified;
        
        private string logMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsVerifyCountInputs
        {
            get
            {
                return this.isVerifyCountInputsField;
            }
            set
            {
                this.isVerifyCountInputsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsVerifyCountInputsSpecified
        {
            get
            {
                return this.isVerifyCountInputsFieldSpecified;
            }
            set
            {
                this.isVerifyCountInputsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string LogMessages
        {
            get
            {
                return this.logMessagesField;
            }
            set
            {
                this.logMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class DumpDataTableResponse : IDMSServiceResponse
    {
        
        private DumpDataTableResponseDump dumpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public DumpDataTableResponseDump Dump
        {
            get
            {
                return this.dumpField;
            }
            set
            {
                this.dumpField = value;
            }
        }
    }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class DumpDataTableResponseDump
    {

        private System.Xml.Linq.XElement[] anyField;

        private System.Xml.Linq.XElement any1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace = "http://www.w3.org/2001/XMLSchema", Order = 0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1", Order = 1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class DataTableResponse : IDMSServiceResponse
    {
     //   private IDMSCommonService.ArrayOfXElement reportField;

        private DataTableResponseReport reportField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public DataTableResponseReport Report
        {
            get
            {
                return this.reportField;
            }
            set
            {
                this.reportField = value;
            }
        }
    }
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class DataTableResponseReport
    {

        private System.Xml.Linq.XElement[] anyField;

        private System.Xml.Linq.XElement any1Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace = "http://www.w3.org/2001/XMLSchema", Order = 0)]
        public System.Xml.Linq.XElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1", Order = 1)]
        public System.Xml.Linq.XElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
   

    /// <remarks/> 
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class DeleteRecordResponse : IDMSServiceResponse
    {
        
        private int deleteRecordField;
        
        private bool deleteRecordFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int DeleteRecord
        {
            get
            {
                return this.deleteRecordField;
            }
            set
            {
                this.deleteRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeleteRecordSpecified
        {
            get
            {
                return this.deleteRecordFieldSpecified;
            }
            set
            {
                this.deleteRecordFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class ListRecordResponse : IDMSServiceResponse
    {
        
        private DWModal[] getListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/DW.Bizness.Common.Services.Modal")]
        public DWModal[] GetList
        {
            get
            {
                return this.getListField;
            }
            set
            {
                this.getListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/CommonService")]
    public partial class QuickCountResponse : IDMSServiceResponse
    {
        
        private int countField;
        
        private bool countFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Count
        {
            get
            {
                return this.countField;
            }
            set
            {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CountSpecified
        {
            get
            {
                return this.countFieldSpecified;
            }
            set
            {
                this.countFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRandomSampleForSegment", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRandomSampleForSegmentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int segmentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool isExportlayout;
        
        public GetRandomSampleForSegmentRequest()
        {
        }
        
        public GetRandomSampleForSegmentRequest(int segmentId, int size, bool isExportlayout)
        {
            this.segmentId = segmentId;
            this.size = size;
            this.isExportlayout = isExportlayout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRandomSampleForSegmentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRandomSampleForSegmentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IDMSCommonService.DumpResponse GetRandomSampleForSegmentResult;
        
        public GetRandomSampleForSegmentResponse()
        {
        }
        
        public GetRandomSampleForSegmentResponse(IDMSCommonService.DumpResponse GetRandomSampleForSegmentResult)
        {
            this.GetRandomSampleForSegmentResult = GetRandomSampleForSegmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQuickCount", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQuickCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int segmentId;
        
        public GetQuickCountRequest()
        {
        }
        
        public GetQuickCountRequest(int segmentId)
        {
            this.segmentId = segmentId;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetReport", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetReportRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        public string reportType;
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
        public int segmentId;
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
        public int reportID;

        public GetReportRequest()
        {
        }

        public GetReportRequest(string reportType, int segmentId, int reportID)
        {
            this.reportType = reportType;
            this.segmentId = segmentId;         
            this.reportID=reportID;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetQuickCountResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetQuickCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IDMSCommonService.QuickCountResponse GetQuickCountResult;
        
        public GetQuickCountResponse()
        {
        }
        
        public GetQuickCountResponse(IDMSCommonService.QuickCountResponse GetQuickCountResult)
        {
            this.GetQuickCountResult = GetQuickCountResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetReportResponse", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
    public partial class GetReportResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public IDMSCommonService.DataTableResponse GetReportResult;

        public GetReportResponse()
        {
        }

        public GetReportResponse(IDMSCommonService.DataTableResponse GetReportResult)
        {
            this.GetReportResult = GetReportResult;
        }
    }

    /// <remarks/>

    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfstringstringKeyValueOfstringstring
    {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDWRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDWRecordsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int databaseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int buildID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfstringstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public IDMSCommonService.ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] search;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int recCount;
        
        public GetDWRecordsRequest()
        {
        }
        
        public GetDWRecordsRequest(int databaseID, int buildID, IDMSCommonService.ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] search, int recCount)
        {
            this.databaseID = databaseID;
            this.buildID = buildID;
            this.search = search;
            this.recCount = recCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDWRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDWRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IDMSCommonService.ListRecordResponse GetDWRecordsResult;
        
        public GetDWRecordsResponse()
        {
        }
        
        public GetDWRecordsResponse(IDMSCommonService.ListRecordResponse GetDWRecordsResult)
        {
            this.GetDWRecordsResult = GetDWRecordsResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public partial class ArrayOfKeyValueOfintstringKeyValueOfintstring
    {
        
        private int keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDWRecords", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDWRecordsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string userLoginID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int databaseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int buildID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("KeyValueOfintstring", Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public IDMSCommonService.ArrayOfKeyValueOfintstringKeyValueOfintstring[] KeyFields;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public bool addToSuppression;
        
        public DeleteDWRecordsRequest()
        {
        }
        
        public DeleteDWRecordsRequest(string userLoginID, int databaseID, int buildID, IDMSCommonService.ArrayOfKeyValueOfintstringKeyValueOfintstring[] KeyFields, bool addToSuppression)
        {
            this.userLoginID = userLoginID;
            this.databaseID = databaseID;
            this.buildID = buildID;
            this.KeyFields = KeyFields;
            this.addToSuppression = addToSuppression;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteDWRecordsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteDWRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IDMSCommonService.DeleteRecordResponse DeleteDWRecordsResult;
        
        public DeleteDWRecordsResponse()
        {
        }
        
        public DeleteDWRecordsResponse(IDMSCommonService.DeleteRecordResponse DeleteDWRecordsResult)
        {
            this.DeleteDWRecordsResult = DeleteDWRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBuildDataFromSybaseIQ", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBuildDataFromSybaseIQRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int iDatabaseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int iBuildID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int sTopNRecodrsToSelect;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sTableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string sFieldName;
        
        public GetBuildDataFromSybaseIQRequest()
        {
        }
        
        public GetBuildDataFromSybaseIQRequest(int iDatabaseID, int iBuildID, int sTopNRecodrsToSelect, string sTableName, string sFieldName)
        {
            this.iDatabaseID = iDatabaseID;
            this.iBuildID = iBuildID;
            this.sTopNRecodrsToSelect = sTopNRecodrsToSelect;
            this.sTableName = sTableName;
            this.sFieldName = sFieldName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBuildDataFromSybaseIQResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBuildDataFromSybaseIQResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IDMSCommonService.DumpDataTableResponse GetBuildDataFromSybaseIQResult;
        
        public GetBuildDataFromSybaseIQResponse()
        {
        }
        
        public GetBuildDataFromSybaseIQResponse(IDMSCommonService.DumpDataTableResponse GetBuildDataFromSybaseIQResult)
        {
            this.GetBuildDataFromSybaseIQResult = GetBuildDataFromSybaseIQResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestCalculatedField", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestCalculatedFieldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IQTableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Formula;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FieldName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int DatabaseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int BuildID;
        
        public TestCalculatedFieldRequest()
        {
        }
        
        public TestCalculatedFieldRequest(string IQTableName, string Formula, string FieldName, int DatabaseID, int BuildID)
        {
            this.IQTableName = IQTableName;
            this.Formula = Formula;
            this.FieldName = FieldName;
            this.DatabaseID = DatabaseID;
            this.BuildID = BuildID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TestCalculatedFieldResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class TestCalculatedFieldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IDMSCommonService.ArrayOfXElement TestCalculatedFieldResult;
        
        public TestCalculatedFieldResponse()
        {
        }
        
        public TestCalculatedFieldResponse(IDMSCommonService.ArrayOfXElement TestCalculatedFieldResult)
        {
            this.TestCalculatedFieldResult = TestCalculatedFieldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoIQOperation", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DoIQOperationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string IQTableName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Formula;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FieldName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string FieldFormat;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int DatabaseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public int BuildID;
        
        public DoIQOperationRequest()
        {
        }
        
        public DoIQOperationRequest(string IQTableName, string Formula, string FieldName, string FieldFormat, int DatabaseID, int BuildID)
        {
            this.IQTableName = IQTableName;
            this.Formula = Formula;
            this.FieldName = FieldName;
            this.FieldFormat = FieldFormat;
            this.DatabaseID = DatabaseID;
            this.BuildID = BuildID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DoIQOperationResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DoIQOperationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DoIQOperationResult;
        
        public DoIQOperationResponse()
        {
        }
        
        public DoIQOperationResponse(string DoIQOperationResult)
        {
            this.DoIQOperationResult = DoIQOperationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SuspendCountSQL", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SuspendCountSQLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ConnectionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int DatabaseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int BuildID;
        
        public SuspendCountSQLRequest()
        {
        }
        
        public SuspendCountSQLRequest(int ConnectionID, int DatabaseID, int BuildID)
        {
            this.ConnectionID = ConnectionID;
            this.DatabaseID = DatabaseID;
            this.BuildID = BuildID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SuspendCountSQLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SuspendCountSQLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SuspendCountSQLResult;
        
        public SuspendCountSQLResponse()
        {
        }
        
        public SuspendCountSQLResponse(string SuspendCountSQLResult)
        {
            this.SuspendCountSQLResult = SuspendCountSQLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateOutputFields", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateOutputFieldsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int OrderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string whatToValidate;
        
        public ValidateOutputFieldsRequest()
        {
        }
        
        public ValidateOutputFieldsRequest(int OrderId, string whatToValidate)
        {
            this.OrderId = OrderId;
            this.whatToValidate = whatToValidate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateOutputFieldsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ValidateOutputFieldsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ValidateOutputFieldsResult;
        
        public ValidateOutputFieldsResponse()
        {
        }
        
        public ValidateOutputFieldsResponse(string ValidateOutputFieldsResult)
        {
            this.ValidateOutputFieldsResult = ValidateOutputFieldsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyCountInputs", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyCountInputsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int orderId;
        
        public VerifyCountInputsRequest()
        {
        }
        
        public VerifyCountInputsRequest(int orderId)
        {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyCountInputsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyCountInputsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public IDMSCommonService.VerifyCountInputs VerifyCountInputsResult;
        
        public VerifyCountInputsResponse()
        {
        }
        
        public VerifyCountInputsResponse(IDMSCommonService.VerifyCountInputs VerifyCountInputsResult)
        {
            this.VerifyCountInputsResult = VerifyCountInputsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportGUIOrder", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImportGUIOrderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GUIOrderNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int DatabaseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserID;
        
        public ImportGUIOrderRequest()
        {
        }
        
        public ImportGUIOrderRequest(int GUIOrderNumber, int DatabaseID, string UserID)
        {
            this.GUIOrderNumber = GUIOrderNumber;
            this.DatabaseID = DatabaseID;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ImportGUIOrderResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ImportGUIOrderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ImportGUIOrderResult;
        
        public ImportGUIOrderResponse()
        {
        }
        
        public ImportGUIOrderResponse(string ImportGUIOrderResult)
        {
            this.ImportGUIOrderResult = ImportGUIOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyFilterValidations", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyFilterValidationsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string questionFieldName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string textValues;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string valueOperator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int buildLayoutID;
        
        public VerifyFilterValidationsRequest()
        {
        }
        
        public VerifyFilterValidationsRequest(string questionFieldName, string textValues, string valueOperator, int buildLayoutID)
        {
            this.questionFieldName = questionFieldName;
            this.textValues = textValues;
            this.valueOperator = valueOperator;
            this.buildLayoutID = buildLayoutID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyFilterValidationsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyFilterValidationsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string VerifyFilterValidationsResult;
        
        public VerifyFilterValidationsResponse()
        {
        }
        
        public VerifyFilterValidationsResponse(string VerifyFilterValidationsResult)
        {
            this.VerifyFilterValidationsResult = VerifyFilterValidationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyGeoRadius", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyGeoRadiusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string address;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int databaseID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mainTableName;
        
        public VerifyGeoRadiusRequest()
        {
        }
        
        public VerifyGeoRadiusRequest(string address, int databaseID, string mainTableName)
        {
            this.address = address;
            this.databaseID = databaseID;
            this.mainTableName = mainTableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VerifyGeoRadiusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class VerifyGeoRadiusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] VerifyGeoRadiusResult;
        
        public VerifyGeoRadiusResponse()
        {
        }
        
        public VerifyGeoRadiusResponse(string[] VerifyGeoRadiusResult)
        {
            this.VerifyGeoRadiusResult = VerifyGeoRadiusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnBillingStatusChange", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OnBillingStatusChangeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idmsOrderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int billingOrderID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string billingStatus;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string billingData;
        
        public OnBillingStatusChangeRequest()
        {
        }
        
        public OnBillingStatusChangeRequest(int idmsOrderID, int billingOrderID, string billingStatus, string billingData)
        {
            this.idmsOrderID = idmsOrderID;
            this.billingOrderID = billingOrderID;
            this.billingStatus = billingStatus;
            this.billingData = billingData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="OnBillingStatusChangeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class OnBillingStatusChangeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string OnBillingStatusChangeResult;
        
        public OnBillingStatusChangeResponse()
        {
        }
        
        public OnBillingStatusChangeResponse(string OnBillingStatusChangeResult)
        {
            this.OnBillingStatusChangeResult = OnBillingStatusChangeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveSummaryReport", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveSummaryReportRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int orderId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string filePath;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fileName;
        
        public SaveSummaryReportRequest()
        {
        }
        
        public SaveSummaryReportRequest(int orderId, string filePath, string fileName)
        {
            this.orderId = orderId;
            this.filePath = filePath;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveSummaryReportResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveSummaryReportResponse
    {
        
        public SaveSummaryReportResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListOfSegmentDump", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListOfSegmentDumpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int segmentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int size;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public bool isExportlayout;
        
        public ListOfSegmentDumpRequest()
        {
        }
        
        public ListOfSegmentDumpRequest(int segmentId, int size, bool isExportlayout)
        {
            this.segmentId = segmentId;
            this.size = size;
            this.isExportlayout = isExportlayout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListOfSegmentDumpResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ListOfSegmentDumpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ListOfSegmentDumpResult;
        
        public ListOfSegmentDumpResponse()
        {
        }
        
        public ListOfSegmentDumpResponse(string ListOfSegmentDumpResult)
        {
            this.ListOfSegmentDumpResult = ListOfSegmentDumpResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface IIDMSIQServiceChannel : IDMSCommonService.IIDMSIQService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class IDMSIQServiceClient : System.ServiceModel.ClientBase<IDMSCommonService.IIDMSIQService>, IDMSCommonService.IIDMSIQService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IDMSIQServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IDMSIQServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IDMSIQServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IDMSIQServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IDMSIQServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.GetRandomSampleForSegmentResponse> IDMSCommonService.IIDMSIQService.GetRandomSampleForSegmentAsync(IDMSCommonService.GetRandomSampleForSegmentRequest request)
        {
            return base.Channel.GetRandomSampleForSegmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.GetRandomSampleForSegmentResponse> GetRandomSampleForSegmentAsync(int segmentId, int size, bool isExportlayout)
        {
            IDMSCommonService.GetRandomSampleForSegmentRequest inValue = new IDMSCommonService.GetRandomSampleForSegmentRequest();
            inValue.segmentId = segmentId;
            inValue.size = size;
            inValue.isExportlayout = isExportlayout;
            return ((IDMSCommonService.IIDMSIQService)(this)).GetRandomSampleForSegmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.GetQuickCountResponse> IDMSCommonService.IIDMSIQService.GetQuickCountAsync(IDMSCommonService.GetQuickCountRequest request)
        {
            return base.Channel.GetQuickCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.GetQuickCountResponse> GetQuickCountAsync(int segmentId)
        {
            IDMSCommonService.GetQuickCountRequest inValue = new IDMSCommonService.GetQuickCountRequest();
            inValue.segmentId = segmentId;
            return ((IDMSCommonService.IIDMSIQService)(this)).GetQuickCountAsync(inValue);
        }
       
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.GetReportResponse> IDMSCommonService.IIDMSIQService.GetReport(IDMSCommonService.GetReportRequest request)
        {
            return base.Channel.GetReport(request);
        }
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.Threading.Tasks.Task<IDMSCommonService.GetReportResponse> GetReport(string reportType, int segmentId, int reportID)
        {
            IDMSCommonService.GetReportRequest inValue = new IDMSCommonService.GetReportRequest();
            inValue.reportType = reportType;
            inValue.segmentId = segmentId;           
            inValue.reportID=reportID;
            return ((IDMSCommonService.IIDMSIQService)(this)).GetReport(inValue);
        }
      
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.GetDWRecordsResponse> IDMSCommonService.IIDMSIQService.GetDWRecordsAsync(IDMSCommonService.GetDWRecordsRequest request)
        {
            return base.Channel.GetDWRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.GetDWRecordsResponse> GetDWRecordsAsync(int databaseID, int buildID, IDMSCommonService.ArrayOfKeyValueOfstringstringKeyValueOfstringstring[] search, int recCount)
        {
            IDMSCommonService.GetDWRecordsRequest inValue = new IDMSCommonService.GetDWRecordsRequest();
            inValue.databaseID = databaseID;
            inValue.buildID = buildID;
            inValue.search = search;
            inValue.recCount = recCount;
            return ((IDMSCommonService.IIDMSIQService)(this)).GetDWRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.DeleteDWRecordsResponse> IDMSCommonService.IIDMSIQService.DeleteDWRecordsAsync(IDMSCommonService.DeleteDWRecordsRequest request)
        {
            return base.Channel.DeleteDWRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.DeleteDWRecordsResponse> DeleteDWRecordsAsync(string userLoginID, int databaseID, int buildID, IDMSCommonService.ArrayOfKeyValueOfintstringKeyValueOfintstring[] KeyFields, bool addToSuppression)
        {
            IDMSCommonService.DeleteDWRecordsRequest inValue = new IDMSCommonService.DeleteDWRecordsRequest();
            inValue.userLoginID = userLoginID;
            inValue.databaseID = databaseID;
            inValue.buildID = buildID;
            inValue.KeyFields = KeyFields;
            inValue.addToSuppression = addToSuppression;
            return ((IDMSCommonService.IIDMSIQService)(this)).DeleteDWRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.GetBuildDataFromSybaseIQResponse> IDMSCommonService.IIDMSIQService.GetBuildDataFromSybaseIQAsync(IDMSCommonService.GetBuildDataFromSybaseIQRequest request)
        {
            return base.Channel.GetBuildDataFromSybaseIQAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.GetBuildDataFromSybaseIQResponse> GetBuildDataFromSybaseIQAsync(int iDatabaseID, int iBuildID, int sTopNRecodrsToSelect, string sTableName, string sFieldName)
        {
            IDMSCommonService.GetBuildDataFromSybaseIQRequest inValue = new IDMSCommonService.GetBuildDataFromSybaseIQRequest();
            inValue.iDatabaseID = iDatabaseID;
            inValue.iBuildID = iBuildID;
            inValue.sTopNRecodrsToSelect = sTopNRecodrsToSelect;
            inValue.sTableName = sTableName;
            inValue.sFieldName = sFieldName;
            return ((IDMSCommonService.IIDMSIQService)(this)).GetBuildDataFromSybaseIQAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.TestCalculatedFieldResponse> IDMSCommonService.IIDMSIQService.TestCalculatedFieldAsync(IDMSCommonService.TestCalculatedFieldRequest request)
        {
            return base.Channel.TestCalculatedFieldAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.TestCalculatedFieldResponse> TestCalculatedFieldAsync(string IQTableName, string Formula, string FieldName, int DatabaseID, int BuildID)
        {
            IDMSCommonService.TestCalculatedFieldRequest inValue = new IDMSCommonService.TestCalculatedFieldRequest();
            inValue.IQTableName = IQTableName;
            inValue.Formula = Formula;
            inValue.FieldName = FieldName;
            inValue.DatabaseID = DatabaseID;
            inValue.BuildID = BuildID;
            return ((IDMSCommonService.IIDMSIQService)(this)).TestCalculatedFieldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.DoIQOperationResponse> IDMSCommonService.IIDMSIQService.DoIQOperationAsync(IDMSCommonService.DoIQOperationRequest request)
        {
            return base.Channel.DoIQOperationAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.DoIQOperationResponse> DoIQOperationAsync(string IQTableName, string Formula, string FieldName, string FieldFormat, int DatabaseID, int BuildID)
        {
            IDMSCommonService.DoIQOperationRequest inValue = new IDMSCommonService.DoIQOperationRequest();
            inValue.IQTableName = IQTableName;
            inValue.Formula = Formula;
            inValue.FieldName = FieldName;
            inValue.FieldFormat = FieldFormat;
            inValue.DatabaseID = DatabaseID;
            inValue.BuildID = BuildID;
            return ((IDMSCommonService.IIDMSIQService)(this)).DoIQOperationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.SuspendCountSQLResponse> IDMSCommonService.IIDMSIQService.SuspendCountSQLAsync(IDMSCommonService.SuspendCountSQLRequest request)
        {
            return base.Channel.SuspendCountSQLAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.SuspendCountSQLResponse> SuspendCountSQLAsync(int ConnectionID, int DatabaseID, int BuildID)
        {
            IDMSCommonService.SuspendCountSQLRequest inValue = new IDMSCommonService.SuspendCountSQLRequest();
            inValue.ConnectionID = ConnectionID;
            inValue.DatabaseID = DatabaseID;
            inValue.BuildID = BuildID;
            return ((IDMSCommonService.IIDMSIQService)(this)).SuspendCountSQLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.ValidateOutputFieldsResponse> IDMSCommonService.IIDMSIQService.ValidateOutputFieldsAsync(IDMSCommonService.ValidateOutputFieldsRequest request)
        {
            return base.Channel.ValidateOutputFieldsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.ValidateOutputFieldsResponse> ValidateOutputFieldsAsync(int OrderId, string whatToValidate)
        {
            IDMSCommonService.ValidateOutputFieldsRequest inValue = new IDMSCommonService.ValidateOutputFieldsRequest();
            inValue.OrderId = OrderId;
            inValue.whatToValidate = whatToValidate;
            return ((IDMSCommonService.IIDMSIQService)(this)).ValidateOutputFieldsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.VerifyCountInputsResponse> IDMSCommonService.IIDMSIQService.VerifyCountInputsAsync(IDMSCommonService.VerifyCountInputsRequest request)
        {
            return base.Channel.VerifyCountInputsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.VerifyCountInputsResponse> VerifyCountInputsAsync(int orderId)
        {
            IDMSCommonService.VerifyCountInputsRequest inValue = new IDMSCommonService.VerifyCountInputsRequest();
            inValue.orderId = orderId;
            return ((IDMSCommonService.IIDMSIQService)(this)).VerifyCountInputsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.ImportGUIOrderResponse> IDMSCommonService.IIDMSIQService.ImportGUIOrderAsync(IDMSCommonService.ImportGUIOrderRequest request)
        {
            return base.Channel.ImportGUIOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.ImportGUIOrderResponse> ImportGUIOrderAsync(int GUIOrderNumber, int DatabaseID, string UserID)
        {
            IDMSCommonService.ImportGUIOrderRequest inValue = new IDMSCommonService.ImportGUIOrderRequest();
            inValue.GUIOrderNumber = GUIOrderNumber;
            inValue.DatabaseID = DatabaseID;
            inValue.UserID = UserID;
            return ((IDMSCommonService.IIDMSIQService)(this)).ImportGUIOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.VerifyFilterValidationsResponse> IDMSCommonService.IIDMSIQService.VerifyFilterValidationsAsync(IDMSCommonService.VerifyFilterValidationsRequest request)
        {
            return base.Channel.VerifyFilterValidationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.VerifyFilterValidationsResponse> VerifyFilterValidationsAsync(string questionFieldName, string textValues, string valueOperator, int buildLayoutID)
        {
            IDMSCommonService.VerifyFilterValidationsRequest inValue = new IDMSCommonService.VerifyFilterValidationsRequest();
            inValue.questionFieldName = questionFieldName;
            inValue.textValues = textValues;
            inValue.valueOperator = valueOperator;
            inValue.buildLayoutID = buildLayoutID;
            return ((IDMSCommonService.IIDMSIQService)(this)).VerifyFilterValidationsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.VerifyGeoRadiusResponse> IDMSCommonService.IIDMSIQService.VerifyGeoRadiusAsync(IDMSCommonService.VerifyGeoRadiusRequest request)
        {
            return base.Channel.VerifyGeoRadiusAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.VerifyGeoRadiusResponse> VerifyGeoRadiusAsync(string address, int databaseID, string mainTableName)
        {
            IDMSCommonService.VerifyGeoRadiusRequest inValue = new IDMSCommonService.VerifyGeoRadiusRequest();
            inValue.address = address;
            inValue.databaseID = databaseID;
            inValue.mainTableName = mainTableName;
            return ((IDMSCommonService.IIDMSIQService)(this)).VerifyGeoRadiusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.OnBillingStatusChangeResponse> IDMSCommonService.IIDMSIQService.OnBillingStatusChangeAsync(IDMSCommonService.OnBillingStatusChangeRequest request)
        {
            return base.Channel.OnBillingStatusChangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.OnBillingStatusChangeResponse> OnBillingStatusChangeAsync(int idmsOrderID, int billingOrderID, string billingStatus, string billingData)
        {
            IDMSCommonService.OnBillingStatusChangeRequest inValue = new IDMSCommonService.OnBillingStatusChangeRequest();
            inValue.idmsOrderID = idmsOrderID;
            inValue.billingOrderID = billingOrderID;
            inValue.billingStatus = billingStatus;
            inValue.billingData = billingData;
            return ((IDMSCommonService.IIDMSIQService)(this)).OnBillingStatusChangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.SaveSummaryReportResponse> IDMSCommonService.IIDMSIQService.SaveSummaryReportAsync(IDMSCommonService.SaveSummaryReportRequest request)
        {
            return base.Channel.SaveSummaryReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.SaveSummaryReportResponse> SaveSummaryReportAsync(int orderId, string filePath, string fileName)
        {
            IDMSCommonService.SaveSummaryReportRequest inValue = new IDMSCommonService.SaveSummaryReportRequest();
            inValue.orderId = orderId;
            inValue.filePath = filePath;
            inValue.fileName = fileName;
            return ((IDMSCommonService.IIDMSIQService)(this)).SaveSummaryReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IDMSCommonService.ListOfSegmentDumpResponse> IDMSCommonService.IIDMSIQService.ListOfSegmentDumpAsync(IDMSCommonService.ListOfSegmentDumpRequest request)
        {
            return base.Channel.ListOfSegmentDumpAsync(request);
        }
        
        public System.Threading.Tasks.Task<IDMSCommonService.ListOfSegmentDumpResponse> ListOfSegmentDumpAsync(int segmentId, int size, bool isExportlayout)
        {
            IDMSCommonService.ListOfSegmentDumpRequest inValue = new IDMSCommonService.ListOfSegmentDumpRequest();
            inValue.segmentId = segmentId;
            inValue.size = size;
            inValue.isExportlayout = isExportlayout;
            return ((IDMSCommonService.IIDMSIQService)(this)).ListOfSegmentDumpAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IIDMSIQService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IDMSIQServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IIDMSIQService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IIDMSIQService,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
