INSERT INTO TBLLOOKUP
(CLOOKUPVALUE, IORDERBY, CCODE, CDESCRIPTION, CFIELD, MFIELD, CCREATEDBY, DCREATEDDATE)
VALUES
('LISTCONVERSIONFREQUENCY', 1, 'D', 'Daily', '','','SYSTEM', GETDATE())

INSERT INTO TBLLOOKUP
(CLOOKUPVALUE, IORDERBY, CCODE, CDESCRIPTION, CFIELD, MFIELD, CCREATEDBY, DCREATEDDATE)
VALUES
('LISTCONVERSIONFREQUENCY', 2, 'W', 'Weekly', '','','SYSTEM', GETDATE())

INSERT INTO TBLLOOKUP
(CLOOKUPVALUE, IORDERBY, CCODE, CDESCRIPTION, CFIELD, MFIELD, CCREATEDBY, DCREATEDDATE)
VALUES
('LISTCONVERSIONFREQUENCY', 3, 'M', 'Monthly', '','','SYSTEM', GETDATE())

INSERT INTO TBLLOOKUP
(CLOOKUPVALUE, IORDERBY, CCODE, CDESCRIPTION, CFIELD, MFIELD, CCREATEDBY, DCREATEDDATE)
VALUES
('LISTCONVERSIONFREQUENCY', 4, 'Y', 'Yearly', '','','SYSTEM', GETDATE())

